from enum import Enum

from tortoise import fields
from tortoise.models import Model

from app.utils import generate_uuid


class PopularQuestionSource(str, Enum):
    seed = "seed"
    auto = "auto"
    manual = "manual"


class PopularQuestion(Model):
    """A frequently-asked citizen question surfaced on the public chat landing page.

    ``source="auto"`` rows are (re)generated by the scheduled ``regenerate`` job;
    editing one flips it to ``manual`` so it survives future churn. A hidden row
    acts as a tombstone: its ``text_key`` blocks the same question from being
    regenerated.
    """

    id = fields.UUIDField(primary_key=True, default=generate_uuid)
    text = fields.TextField()
    text_key = fields.CharField(max_length=500, unique=True)
    agency = fields.ForeignKeyField(
        "models.Agency",
        related_name="popular_questions",
        on_delete=fields.SET_NULL,
        null=True,
    )
    source = fields.CharEnumField(PopularQuestionSource, max_length=10, default=PopularQuestionSource.manual)
    pinned = fields.BooleanField(default=False)
    hidden = fields.BooleanField(default=False)
    sort_order = fields.IntField(default=0)
    score = fields.FloatField(null=True)

    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)

    class Meta:
        table = "popular_questions"
        ordering = ["-pinned", "sort_order", "-created_at"]

    def __str__(self) -> str:
        return self.text[:60]
