from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE "agencies" ADD "stats_reset_at" TIMESTAMPTZ;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE "agencies" DROP COLUMN "stats_reset_at";"""


# NOTE: MODELS_STATE below is carried forward from migration 17 unchanged.
# Aerich could not be run interactively in this environment (it prompted to
# remove an existing file when its internal state diverged from disk).
# The MODELS_STATE blob must be regenerated by running:
#   aerich migrate --name agency_add_stats_reset_at
# in an environment where aerich's DB state is current (after applying all
# prior migrations), before running the next aerich-generated migration.
MODELS_STATE = (
    "eJztXW1zqzYW/iuMP3VnsncT56XdOzs74+S6rbfJTfYm2e206VAZFFsbQFSIJJ7O/e8ryQ"
    "aDEBjZYIPNl7xIenh5JI7OOTo6+rPnYhs6wYfBBHrWrPfR+LPnAReyP6SaI6MHfH9Zzgso"
    "GDuiKeBtEBSFYBxQAizKyp+BE0BWZMPAIsinCHu89Q/4FRLPhR41BHBmiEt+4GgbWwyOvE"
    "lRwyfvBhGCSWDQKTR+j+7+uyEeyHgm2BU1mKAJ8oBj3Ic+GIMAGoE1hS4Qdwo99EcITYon"
    "kLUl7H6//saKkWfDd/Ymi3/9F/MZQcdOMYNsfgFRbtKZL8oeH0efvhct+VuMTQs7oestW/"
    "szOsVe3DwMkf2BY3gde35IAIV2gjMvdJwFvVHR/IlZASUhjB/VXhbY8BmEDme+94/n0LM4"
    "4QbrtQ8hRawno9uY/Ob/7GU6ht9S6oJFkYU93qnIo5yYP7/OX3FJgCjt8fte/Tj48s3pxV"
    "/EK+OAToioFPT0vgogoGAOFSQvWRW/M7xeTQFR8xq1l5hlD7oOp1HBktTl6I1YjQhaj7We"
    "C95NB3oTOmX/9s/PC2j8z+CLYJK1ElRi9kXNP7XPi6r+vI5TuqQwmGJCTV0i06i16FwMwJ"
    "2xeX5cgszz41wueVWaSgdPsA6JUftW0tcvQ18/n75+hr7kY2VYfIDvVM2iBGsJmQXkPQx/"
    "fuDP7AbBH06StG9uBj8LPt3Zoub69vMPUfMEyVfXt5cSuez2HhTSfU6NcpgOvdAVJI/Ysw"
    "LPghmyFZfZniztDe5G2Smod3N199FgP548Vv/RYD/YX/0B+6s/kPWDMiP7pMzIPskf2SeZ"
    "kc3IpGGwLudL9BapZtoYeoUKtm0CnulHQ/x68ubNPhrz30+eyzmFHn+Pj0binyfPRgF/IJ"
    "tBF3+t0zfVSx0QUmwmnjTbS5cYOxB4aumjgkvdNGb4uvpJrS5XIYUub2+vU1LociSLmceb"
    "yyH7EgTZrBGionj0+UEW7Fx9CyysEjv/ur/9nCPXUyiJ00ePvemvNrLokeGggP5W24ew1I"
    "rHIXIo8oIP/IY16cKcjmLZL4t5SWnmF8jKfgcTHcUkBrRkMq1bsYOe7WN2MzMkjg6PMq6V"
    "dJ4cH5ebEI+LpsRjleCdmi4zpLHCNM7nVIK1ktLqR6hgZQqBDbU+dAnWSjJPyg7PotEp88"
    "k9P6YP2A002EyBWsllLR4G4CPzBc60fQwyrpWM1jI6hUfOQS6iJvHdLKcjL8dWzgIlUtlL"
    "NJPUCb/PX/snZ9+efXd6cfYdayIeJS75toDmrEpKIHvygJrPmLiA6ozKLLKV47KGKYh9rp"
    "HCo7B18xX9DLDT9dfX9VmVz54AmvNlC51+UEC7nli/J/iwDnxomQS86fgzZVxLxMu2HZrw"
    "nXHE3p8pXDMHA4UNkT/SVdgKhnqjSK9tTM/NBW0Jn4DtiOp9ECo+QZggOtPQ+ZKQQ9X2cE"
    "ghMaeL9y0riSXYFr3v9YzIWuSwjQJm8lpTkyIXMsJMhWTIHZtq8IGOUtfyTYqxo20oZ4At"
    "URm24HtgdxSGmmdBk0AfE4UAyJ+31OhOUygxUVFMgWNawHF05IGEWksQrCVxj5sjBtirsd"
    "uZoa/n11liDpk1G78pgkdW8RahDpI5i0D+cqbKDfaJ1fCpOUc8ppASefYC+iH6oy4qN5yD"
    "2DvYt54zW0jlIvVpdDO8fxjc3KWE5afBw5DX9FP6U1T6zYUkQOOLGP8dPfxo8H+NX24/D2"
    "WZGrd7+KXHn0nEGXj4zQR2InozKo2ISXVs6Ntrdmwa2XXsTjtWPDyPK35+ScTA8oIxsF7e"
    "ALHNVI0y5svBE8U8fLm4wPc/fYEOyImgW8R0X8UXu8aTJqs4y9Jlzy85mWDHhp4pfPjs+h"
    "uS8oO42r8XF2vmh5BLCx9CuI/zBlW2yu27cgnwwEQ8Nb83v1O0AyC0EeUDRbU7IKo7Ktwf"
    "wFvF43blDoF8Orqg/TqMhg2C9lk3YmLqcZvEbMBwo+yulRTKlEEXIK34IwnWuQUSfCqjzA"
    "up3CTAfOd7R6pf78Xj/zF9oCCaXE2kBGvlmDwtQ+ZpPpmneWSqhOJKKpVSsR1EXpyVIPLi"
    "LJdIXiVvIqFKIVkQZxwjOsfe0WrHXucu2Aurcu4u0DAr67QW0ralwmTIGJ/5doPC6O2Mh7"
    "0yHlqgufUoDOgG3NWtu5XaDZi7Jra7HYCVGhaVbyUr2uanJnMXW/uazaHD3tazZqars2yY"
    "Bh3kKk6e3lu0bzpH7+0CWzpFd98UXVXs/xjbiji6gnAwCbc1i7tNX00cRK7PrgTs6FXQ68"
    "IgYDaUpvc8jTpE/3kQIJ5dgZrrEZiHP0QqRVYtXf6SoAMhLeNbkTnMEvg9JhBNvJ/gTNCY"
    "zAiiXn9eJlprKnGZZecjHnX1FvtL0kODvSF7LzhPJHE1uL8afBr2vu7MKfUKSQAWL67ySS"
    "3rj1a4pOKWJfPdMZORGkmc8RT2j0/ODDeZxS51Yb1UdqmkebXfrXOjNcyNRhF1tNw+MWCL"
    "xuJTeAz7gP88+bv4+e3y79M+/3l2KtqMxc8TUfJdhW63cn63Isdbxr/hE/iKoNaGwASkJY"
    "t829aKk7lES+9JS2C6ba7rrwe2w+nZC0LLYqp7ZcKhes9nZFlYOFRtU8t1fmZwB+n/jN0H"
    "kUut7GjMAFsiY2vPefVOIWH6nBmw8cVXe/RiU3LgrSS3lhwunXt5T93L3baLvejYzM6BMI"
    "C6UcsJSOf04mRU4PJ6XFymqaStdHglBkXK3XU/fDA+P15fF/m7MtrihvtXbuZXaaYo2cnG"
    "leErcL7AYP78GZ9fovaoyOMHWTuTiIZdBNqeuc4Ci4kshSBzMMix0GKERO4zhzT621NR9+"
    "n28fJ6aNx9GV6N7kcLj0I8T4tKXrRMCP1lOLiWHTZe8KaaDQqyYsWILlpF5QL7X2hPeJIK"
    "EOidniDjOna7WKC91emzxpq0HVhTv1ejq5xCW6rrS8RUoPa3eae1bAGoh02T1r6H79AK+Y"
    "kelwTB555KE063KNaGo7bmmDfuNOI904jZTSjUS62XgHQah0rjaMmyGn6pbEXt5KKMk13W"
    "FRI+9gvZxR6/8Rp6m4ztNLcGaG4N2a4o6SKK2TGrreTPjqqMNN3suD+zY74SnD89JjFt2R"
    "m27RkyTuJNsY8srdgfBbQLAepSAnRzrOQd2Wmsf7NEWJuC/Rvs+tgo2j8V7RUtra2/+Jle"
    "zGsPp7Wuf1477qNYElZotXFdoT7rOK4Zxs06RXZvFFnR1zoeiRjQFhV2C2F/fkgY7VoRqg"
    "lIO4msPl2aT7DrUyYbXqAqhWvBWSgS7iBjpS1GApt2RQoXXQaV2ANlMaBsolNMNQWhIEnQ"
    "mtEgjQoHrCIYpAusLDUxN8Qsaytpyd2rmtQpoAdIYHQcr+awS6EOkLbOObZHzrGGLEBFYd"
    "sKGz0R0Z1voieDx1fnIhh5NnpFdggcw+KJAhZo4w3RKWL2aypzQDa5gD68s/wbZvn7gEBP"
    "nZ06n9wU6AAFP8F6GRai9u208avfD92WqKJ2rZpyM4CaAYW+draEBKxbLd0gYQIOiaWXqy"
    "IB6Zhfn/n5aX9aMjlGtHTjeikHdoH/WhbKzxDaXIc1KRPCOqI5A2wJoduWzyvyWOSfZLki"
    "jcWhHKJssZebYKJYby9IaZ7AtGRY1p39I/YW6udUilE7Ok5lH2YqKNLu6VC/RHS0r0+7O4"
    "a2rakjpEAtFR/HZVPdFSe767Lc7LX3s8tys3cdm8ly05hlsmb5YjT8ft1ydgnCCuJlLSmv"
    "8oZRs3Ka5sYOu5Wxs4rvSx1BK4/GClg86KxLdS7lRWHKwRT5PcV6Xqr+qGhRjyRa1rCJ7N"
    "deEKaPbo3+n7NKEvHW0hmvy3NKf+vW8Xa5jif3YFkTR8a1ZXGl9gPfwvxje/NHaxp1iCpS"
    "UlaUdsXn7+doyfir7dRo3c+5iiO495dNvY+56Azug/iWOw/PXjgCGhXfdg8pnbOe0Yejqk"
    "JVOJg32mEqhReotQK1aF6NJF6tu1a7xlzZLql8xfUVOKFiistfbo4BbZnctr3OnCBSY5ym"
    "Uds8vmN+7YbaAROCQ1+HxxjQluFZ93ozCswAMoVAoURcYuxA4OVY/kmcROaYAetiU3cqKf"
    "+1X97eXqe+9suR/Dk/3lwOmUgV9C53VmVjIbo1mr1QzbInESx6Z6ylY6RRrVyo7p+flxHd"
    "5+f5spvXKZYfdqPnCq+6QsmNvO35Gi53Z5fcvjGwXeT9jQMMYIlDooxnTMSZjYORwY9+HG"
    "Nq3GFCgZPdvaGFfvLuQBC8YWIHBiDQCCgm0DZAYIwtMvOpMQXBFAbR6ZIefGWX9R3e20yT"
    "6/Z+NNFnDF2AtLI+xIA2WjOVSZikvLZRwAb5zBT/azAp4w5bZicZFXLENv2FtNEhVQFtqx"
    "Jew/Gkzd+0FK9oN9QWBK9MkhIzJFpCM41q5Ydey3hk9h1TbtCrYlCusguXuC3ahfHk1GCz"
    "kM39cJEDR28BLgVr5RitZTJKEGPCdx8R1eauYns75xIVGN6NCgprkp0dvXZhlGu3uLUXHp"
    "QufHlPOzZOh1nSmaOOMt0wj6hmhGlzYiRTX8S2D5RsKA2LfEUb0sAdeIO70U+wZel6a00t"
    "myAlx+e5pKzY82kme6mEB/RuZPDWwnMpPKcGxdydyQar7MlkbRVOUM0LPHlDYE05xECBAY"
    "IAW4j3v8h5YwBj7k71bO4PNRANDPzmGT4kLhJnpQeiTuiBXVKcxjpGdb15G3nxdu5tqsVy"
    "4onhuD9Oh8YkphIbdLsO5ouzEjRenOWyyKuyJPoEPqN3XRqXqHacwVX3eVEOEMlZ1zILZG"
    "xnuu/YdF+4UdboyjSy68gddySBr/hlrW8yjew6ctcdyXU5B7mImsR3s52Zn9smAzzU5Dad"
    "O3IfvFYKd+Su9ow3K9J5/U3j293m3CCPzVHJfc47PlB6AAmypj2F32dRc1Tk8wHLNo05Ty"
    "h3tlJ+k4oZatF7O419qmR+Kti2AUmguc0zAekcJQmvtNb2gkXzdhJYy7FLucmE8zOq5ScT"
    "3lrS1dom2sqyp+00kPrr/wHFeubX"
)
