"""initial

Revision ID: 7ca7478d3f3d
Revises: 
Create Date: 2026-03-17 19:10:40.387881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7ca7478d3f3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('connection_type', sa.String(length=50), server_default='API', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_scope', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('total_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('api_key_name', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.String(length=100), nullable=True),
    sa.Column('auth_header', sa.String(length=255), nullable=True),
    sa.Column('base_path', sa.Text(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('request_format', sa.String(length=100), nullable=True),
    sa.Column('api_endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_spec_raw', sa.Text(), nullable=True),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('agencies', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='success', nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('response_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('connection_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='app_role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    # Seed default agencies
    op.execute("""
        INSERT INTO agencies (id, name, short_name, logo, connection_type, status, description, data_scope, color, endpoint_url)
        VALUES
            (
                gen_random_uuid(),
                'สำนักงานคณะกรรมการอาหารและยา',
                'อย.',
                '🏥',
                'MCP',
                'active',
                'ตรวจสอบทะเบียนยา อาหาร และเครื่องสำอาง',
                ARRAY['ยา', 'อาหาร', 'เครื่องสำอาง', 'ผลิตภัณฑ์สุขภาพ'],
                'hsl(145 55% 40%)',
                'https://api.fda.moph.go.th'
            ),
            (
                gen_random_uuid(),
                'กรมสรรพากร',
                'สรรพากร',
                '💰',
                'A2A',
                'active',
                'ข้อมูลภาษีเงินได้ ภาษีมูลค่าเพิ่ม และการยื่นแบบ',
                ARRAY['ภาษีเงินได้', 'VAT', 'ลดหย่อนภาษี', 'ยื่นแบบออนไลน์'],
                'hsl(213 70% 45%)',
                'https://api.rd.go.th'
            ),
            (
                gen_random_uuid(),
                'กรมการปกครอง',
                'ปกครอง',
                '🏛️',
                'API',
                'active',
                'ทะเบียนราษฎร บัตรประชาชน และเอกสารพลเมือง',
                ARRAY['บัตรประชาชน', 'ทะเบียนบ้าน', 'แจ้งเกิด-ตาย', 'เปลี่ยนชื่อ'],
                'hsl(25 85% 55%)',
                'https://api.dopa.go.th'
            ),
            (
                gen_random_uuid(),
                'กรมที่ดิน',
                'ที่ดิน',
                '🗺️',
                'MCP',
                'active',
                'โฉนดที่ดิน การจดทะเบียน และราคาประเมิน',
                ARRAY['โฉนดที่ดิน', 'ราคาประเมิน', 'รังวัด', 'จดทะเบียนสิทธิ'],
                'hsl(280 50% 50%)',
                'https://api.dol.go.th'
            )
        ON CONFLICT DO NOTHING
    """)

    # Create default admin user (password: admin1234)
    op.execute("""
        INSERT INTO users (id, email, hashed_password, display_name, is_admin)
        VALUES (
            gen_random_uuid(),
            'admin@example.com',
            '$2b$12$NCcVNchz3WFC1.A733rm7.0DECPPhIgG8fNJDAku4.KaBWJ.PmsGy',
            'Admin',
            TRUE
        )
        ON CONFLICT DO NOTHING
    """)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('messages')
    op.drop_table('connection_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_table('conversations')
    op.drop_table('agencies')
    # ### end Alembic commands ###
